version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 12
  pre_build:
    commands:
      - echo installing dependencies...
      - npm i -g @angular/cli
      - npm install
  build:
    commands:
      # - echo testing...
      # - echo building...
      - ng build
  post_build:
    commands:
      - mv appspec.yml ./dist
      - mv scripts ./dist
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: 'dist'
